# .github/release-drafter.yml
name-template: 'Next Release'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
prerelease-version-template: '$MAJOR.$MINOR.$PATCHb$ITERATION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'test'
      - 'build'
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed
  $CHANGES

  ## New Contributors
  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
