# .github/release-drafter.yml
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
prerelease-version-template: '$MAJOR.$MINOR.$PATCHb$ITERATION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'test'
      - 'build'
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  Thanks to all contributors!
