name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: ["Prepare Release"]
    types:
      - completed

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout for push/pr
        if: github.event_name != 'workflow_run'
        uses: actions/checkout@v4

      - name: Checkout code from triggering workflow
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"