name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  create:

permissions: {}

jobs:
  validate-hacs:
    # Run on push/pr to main, or on creation of a release branch
    if: github.event_name != 'create' || (github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release/'))
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # On create events, checkout the new branch
          ref: ${{ github.event_name == 'create' && github.event.ref || '' }}

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"